[package]
name = "rust-cc-benchmarks"
description = "Benchmarks for rust-cc and other garbage collectors implemented in the Rust programming language"
version = "0.1.0"
authors = ["fren_gor <goro@frengor.com>"]
readme = "README.md"
repository = "https://github.com/frengor/rust-cc-benchmarks"
license = "MIT OR Apache-2.0"
edition = "2021"

publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# To allow the --verbose option to work with cargo (see Criterion FAQ)
[[bin]]
name = "rust-cc-benchmarks"
bench = false

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.3"
parking_lot = { version = "=0.11", optional = true } # For mgc benchmarks

rust-cc = { version = "0.6.1", optional = true, default-features = false, features = ["std", "derive", "auto-collect"] }
#rust-cc = { git = "https://github.com/frengor/rust-cc", branch = "dev", optional = true, default-features = false, features = ["std", "derive", "auto-collect"] }
gc = { git = "https://github.com/Manishearth/rust-gc", features = ["derive"], optional = true }
zb-safe-gc = { git = "https://github.com/ZainlessBrombie/rs-safe-gc", package = "safe-gc", optional = true }
safe-gc = {  version = "1.0.0", optional = true }
shredder = { version = "0.2.0", optional = true }
mgc = { git = "https://github.com/sunjay/mgc", optional = true }
broom = { version = "0.3.2", optional = true }
bacon_rajan_cc = { version = "0.4.0", optional = true }

[features]
default = [
    "stress-test", "binary-trees", "binary-trees-with-parent-pointers", "large-linked-list",
    "rust-cc", "rc", "arc", "gc", "bacon-rajan-cc", "safe-gc", "broom",
    "rust-cc-mark-alive", "rust-cc-finalization",
]

# General features
rust-cc-mark-alive = []
rust-cc-finalization=["rust-cc/finalization"]
jemalloc = ["dep:tikv-jemallocator"]

# Benchmarks
stress-test = []
binary-trees = []
binary-trees-with-parent-pointers = []
large-linked-list = []

# Garbage collectors
rc = []
arc = []
rust-cc = ["dep:rust-cc"]
gc = ["dep:gc"]
zb-safe-gc = ["dep:zb-safe-gc"]
safe-gc = ["dep:safe-gc"]
shredder = ["dep:shredder"]
mgc = ["dep:mgc", "dep:parking_lot"]
broom = ["dep:broom"]
bacon-rajan-cc = ["dep:bacon_rajan_cc"]

[[bench]]
name = "bench"
harness = false

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[profile.bench]
codegen-units = 1
lto = "thin"
